/**
 * Mock data del módulo delivery — vive separado para que el day cuando movamos
 * a backend solo borremos este archivo y cambiemos el delivery.service.ts.
 */

import { FeaturedProduct, Product, ProductCategory } from '@/types/api';

export const MOCK_CATEGORIES: ProductCategory[] = [
  { id: 'cat-burgers', residencyId: 'mock', name: 'Hamburguesas', slug: 'burgers', icon: 'box', sortOrder: 1, active: true, productCount: 4 },
  { id: 'cat-tacos', residencyId: 'mock', name: 'Tacos', slug: 'tacos', icon: 'circle', sortOrder: 2, active: true, productCount: 3 },
  { id: 'cat-pizza', residencyId: 'mock', name: 'Pizza', slug: 'pizza', icon: 'pie-chart', sortOrder: 3, active: true, productCount: 2 },
  { id: 'cat-sushi', residencyId: 'mock', name: 'Sushi', slug: 'sushi', icon: 'feather', sortOrder: 4, active: true, productCount: 2 },
  { id: 'cat-bowls', residencyId: 'mock', name: 'Bowls', slug: 'bowls', icon: 'inbox', sortOrder: 5, active: true, productCount: 2 },
  { id: 'cat-drinks', residencyId: 'mock', name: 'Bebidas', slug: 'drinks', icon: 'coffee', sortOrder: 6, active: true, productCount: 3 },
  { id: 'cat-desserts', residencyId: 'mock', name: 'Postres', slug: 'desserts', icon: 'heart', sortOrder: 7, active: true, productCount: 2 },
];

export const MOCK_PRODUCTS: Product[] = [
  // ---- Hamburguesas ----
  {
    id: 'p-burger-classic',
    residencyId: 'mock',
    categoryId: 'cat-burgers',
    name: 'Classic Smash Burger',
    description: 'Doble carne de res 100 g, queso americano, cebolla caramelizada, pepinillos y salsa de la casa en pan brioche.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=1200&auto=format&fit=crop',
    price: 159,
    originalPrice: 189,
    status: 'available',
    rating: 4.8,
    reviewCount: 234,
    prepTime: '15-25 min',
    tags: ['nuevo'],
    featured: true,
    optionGroups: [
      {
        id: 'g-burger-size',
        name: 'Tamaño',
        mode: 'single',
        required: true,
        options: [
          { id: 'sz-single', name: 'Sencilla', priceDelta: 0, available: true, default: true },
          { id: 'sz-double', name: 'Doble carne', priceDelta: 45, available: true },
          { id: 'sz-triple', name: 'Triple carne', priceDelta: 85, available: true },
        ],
      },
      {
        id: 'g-burger-cheese',
        name: 'Tipo de queso',
        mode: 'single',
        required: true,
        options: [
          { id: 'ch-american', name: 'Americano', priceDelta: 0, available: true, default: true },
          { id: 'ch-cheddar', name: 'Cheddar', priceDelta: 10, available: true },
          { id: 'ch-blue', name: 'Azul', priceDelta: 20, available: true },
          { id: 'ch-none', name: 'Sin queso', priceDelta: 0, available: true },
        ],
      },
      {
        id: 'g-burger-extras',
        name: 'Extras',
        mode: 'multiple',
        required: false,
        maxSelections: 5,
        options: [
          { id: 'ex-bacon', name: 'Tocino', priceDelta: 25, available: true },
          { id: 'ex-egg', name: 'Huevo estrellado', priceDelta: 15, available: true },
          { id: 'ex-avocado', name: 'Aguacate', priceDelta: 20, available: true },
          { id: 'ex-jalapeno', name: 'Jalapeños', priceDelta: 8, available: true },
          { id: 'ex-onion', name: 'Cebolla extra', priceDelta: 5, available: true },
        ],
      },
      {
        id: 'g-burger-side',
        name: 'Acompañamiento',
        mode: 'single',
        required: true,
        options: [
          { id: 'sd-fries', name: 'Papas a la francesa', priceDelta: 0, available: true, default: true },
          { id: 'sd-sweet', name: 'Papas dulces', priceDelta: 15, available: true },
          { id: 'sd-onion', name: 'Aros de cebolla', priceDelta: 25, available: true },
          { id: 'sd-salad', name: 'Ensalada de la casa', priceDelta: 10, available: true },
        ],
      },
    ],
  },
  {
    id: 'p-burger-mushroom',
    residencyId: 'mock',
    categoryId: 'cat-burgers',
    name: 'Truffle Mushroom Burger',
    description: 'Hamburguesa de res con champiñones salteados al ajo, queso suizo y aceite de trufa.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=1200&auto=format&fit=crop',
    price: 199,
    status: 'available',
    rating: 4.7,
    reviewCount: 142,
    prepTime: '20-30 min',
    optionGroups: [],
  },
  {
    id: 'p-burger-veggie',
    residencyId: 'mock',
    categoryId: 'cat-burgers',
    name: 'Veggie Beet Burger',
    description: 'Hamburguesa de betabel y quinoa con queso de cabra y aioli de chipotle.',
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?q=80&w=1200&auto=format&fit=crop',
    price: 169,
    status: 'available',
    rating: 4.6,
    reviewCount: 88,
    prepTime: '15-25 min',
    tags: ['veggie'],
    optionGroups: [],
  },
  {
    id: 'p-burger-chicken',
    residencyId: 'mock',
    categoryId: 'cat-burgers',
    name: 'Crispy Chicken Burger',
    description: 'Pechuga de pollo crujiente, lechuga romana y mayonesa de chipotle.',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?q=80&w=1200&auto=format&fit=crop',
    price: 149,
    status: 'sold_out',
    rating: 4.5,
    reviewCount: 65,
    prepTime: '15-20 min',
    optionGroups: [],
  },

  // ---- Tacos ----
  {
    id: 'p-tacos-pastor',
    residencyId: 'mock',
    categoryId: 'cat-tacos',
    name: 'Tacos al Pastor',
    description: 'Orden de 4 tacos al pastor con piña, cilantro y cebolla.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=1200&auto=format&fit=crop',
    price: 119,
    status: 'available',
    rating: 4.9,
    reviewCount: 412,
    prepTime: '10-15 min',
    optionGroups: [
      {
        id: 'g-tacos-tortilla',
        name: 'Tortilla',
        mode: 'single',
        required: true,
        options: [
          { id: 'tt-corn', name: 'Maíz', priceDelta: 0, available: true, default: true },
          { id: 'tt-flour', name: 'Harina', priceDelta: 5, available: true },
        ],
      },
      {
        id: 'g-tacos-salsa',
        name: 'Salsas',
        mode: 'multiple',
        required: false,
        maxSelections: 3,
        options: [
          { id: 'sa-verde', name: 'Verde', priceDelta: 0, available: true },
          { id: 'sa-roja', name: 'Roja', priceDelta: 0, available: true },
          { id: 'sa-habanero', name: 'Habanero', priceDelta: 0, available: true },
          { id: 'sa-guac', name: 'Guacamole', priceDelta: 25, available: true },
        ],
      },
    ],
  },
  {
    id: 'p-tacos-suadero',
    residencyId: 'mock',
    categoryId: 'cat-tacos',
    name: 'Tacos de Suadero',
    description: 'Orden de 4 tacos de suadero con cebolla y cilantro.',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?q=80&w=1200&auto=format&fit=crop',
    price: 129,
    status: 'available',
    rating: 4.7,
    reviewCount: 198,
    prepTime: '10-15 min',
    optionGroups: [],
  },
  {
    id: 'p-tacos-camaron',
    residencyId: 'mock',
    categoryId: 'cat-tacos',
    name: 'Tacos de Camarón',
    description: '3 tacos de camarón a la diabla con col morada y mayonesa cilantro-limón.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?q=80&w=1200&auto=format&fit=crop',
    price: 159,
    status: 'available',
    rating: 4.8,
    reviewCount: 124,
    prepTime: '15-20 min',
    optionGroups: [],
  },

  // ---- Pizza ----
  {
    id: 'p-pizza-margherita',
    residencyId: 'mock',
    categoryId: 'cat-pizza',
    name: 'Pizza Margherita',
    description: 'Salsa de tomate San Marzano, mozzarella fior di latte y albahaca fresca.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200&auto=format&fit=crop',
    price: 219,
    status: 'available',
    rating: 4.9,
    reviewCount: 312,
    prepTime: '20-30 min',
    optionGroups: [
      {
        id: 'g-pizza-size',
        name: 'Tamaño',
        mode: 'single',
        required: true,
        options: [
          { id: 'pz-personal', name: 'Personal (25 cm)', priceDelta: 0, available: true, default: true },
          { id: 'pz-medium', name: 'Mediana (32 cm)', priceDelta: 70, available: true },
          { id: 'pz-large', name: 'Grande (40 cm)', priceDelta: 140, available: true },
        ],
      },
    ],
  },
  {
    id: 'p-pizza-pepperoni',
    residencyId: 'mock',
    categoryId: 'cat-pizza',
    name: 'Pizza Pepperoni',
    description: 'Pepperoni curado en casa, mozzarella y orégano.',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=1200&auto=format&fit=crop',
    price: 239,
    status: 'available',
    rating: 4.8,
    reviewCount: 287,
    prepTime: '20-30 min',
    optionGroups: [],
  },

  // ---- Sushi ----
  {
    id: 'p-sushi-roll',
    residencyId: 'mock',
    categoryId: 'cat-sushi',
    name: 'Roll Spicy Tuna',
    description: 'Atún picante, pepino, aguacate y cebollín con sésamo.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=1200&auto=format&fit=crop',
    price: 189,
    status: 'available',
    rating: 4.7,
    reviewCount: 156,
    prepTime: '15-20 min',
    optionGroups: [],
  },
  {
    id: 'p-sushi-salmon',
    residencyId: 'mock',
    categoryId: 'cat-sushi',
    name: 'Salmón Nigiri (8 pzs)',
    description: 'Ocho piezas de nigiri de salmón fresco sobre arroz sazonado.',
    image: 'https://images.unsplash.com/photo-1563612116625-3012372fccce?q=80&w=1200&auto=format&fit=crop',
    price: 229,
    status: 'available',
    rating: 4.9,
    reviewCount: 211,
    prepTime: '15-20 min',
    optionGroups: [],
  },

  // ---- Bowls ----
  {
    id: 'p-bowl-poke',
    residencyId: 'mock',
    categoryId: 'cat-bowls',
    name: 'Poke Bowl Atún',
    description: 'Atún rojo, arroz de sushi, edamame, mango, aguacate y aderezo ponzu.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1200&auto=format&fit=crop',
    price: 179,
    status: 'available',
    rating: 4.8,
    reviewCount: 178,
    prepTime: '10-15 min',
    tags: ['saludable'],
    optionGroups: [],
  },
  {
    id: 'p-bowl-buddha',
    residencyId: 'mock',
    categoryId: 'cat-bowls',
    name: 'Buddha Bowl',
    description: 'Quinoa, garbanzos rostizados, kale, betabel, aguacate y aderezo tahini.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop',
    price: 159,
    status: 'available',
    rating: 4.6,
    reviewCount: 92,
    prepTime: '10-15 min',
    tags: ['veggie', 'saludable'],
    optionGroups: [],
  },

  // ---- Bebidas ----
  {
    id: 'p-drink-lemonade',
    residencyId: 'mock',
    categoryId: 'cat-drinks',
    name: 'Limonada de la casa',
    description: 'Limonada fresca con menta y un toque de jengibre.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=1200&auto=format&fit=crop',
    price: 49,
    status: 'available',
    prepTime: '5 min',
    optionGroups: [],
  },
  {
    id: 'p-drink-iced-latte',
    residencyId: 'mock',
    categoryId: 'cat-drinks',
    name: 'Iced Latte',
    description: 'Espresso doble sobre hielo con leche entera o vegetal.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=1200&auto=format&fit=crop',
    price: 65,
    status: 'available',
    prepTime: '5 min',
    optionGroups: [],
  },
  {
    id: 'p-drink-kombucha',
    residencyId: 'mock',
    categoryId: 'cat-drinks',
    name: 'Kombucha de jamaica',
    description: 'Kombucha artesanal con jamaica y jengibre.',
    image: 'https://images.unsplash.com/photo-1597518030269-0e1ed14ad8d6?q=80&w=1200&auto=format&fit=crop',
    price: 75,
    status: 'available',
    prepTime: '5 min',
    optionGroups: [],
  },

  // ---- Postres ----
  {
    id: 'p-dessert-brownie',
    residencyId: 'mock',
    categoryId: 'cat-desserts',
    name: 'Brownie con helado',
    description: 'Brownie de chocolate con bola de helado de vainilla y caramelo salado.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1200&auto=format&fit=crop',
    price: 89,
    status: 'available',
    rating: 4.9,
    reviewCount: 145,
    prepTime: '10 min',
    optionGroups: [],
  },
  {
    id: 'p-dessert-cheesecake',
    residencyId: 'mock',
    categoryId: 'cat-desserts',
    name: 'Cheesecake de fresa',
    description: 'Cheesecake estilo NY con coulis de fresa fresca.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=1200&auto=format&fit=crop',
    price: 95,
    status: 'available',
    rating: 4.7,
    reviewCount: 108,
    prepTime: '5 min',
    optionGroups: [],
  },
];

export const MOCK_FEATURED: FeaturedProduct = {
  productId: 'p-burger-classic',
  product: MOCK_PRODUCTS[0],
  headline: 'Hoy: Classic Smash con 15% off',
  subheadline: 'Solo por hoy en tu residencia. Pídela antes de las 11pm.',
  validUntil: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
};
